# Generated by Django 2.2.16 on 2021-01-26 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='文章类别')),
            ],
            options={
                'verbose_name': '文章类别',
                'verbose_name_plural': '文章类别',
                'db_table': 'category_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='文章标签')),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
                'db_table': 'tag_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='正文')),
                ('sys_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sys_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击量')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_admin.Category', verbose_name='博客类别')),
                ('tag', models.ManyToManyField(to='blog_admin.Tag', verbose_name='博客标签')),
            ],
            options={
                'verbose_name': '我的博客',
                'verbose_name_plural': '我的博客',
                'db_table': 'blog_info',
                'managed': True,
            },
        ),
    ]
